url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: Asim Alrimi # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-tailwind

tailwind:
  input: assets/css/app.css
  minify: true

